---
- name: Create minio binary dir if necesary
  file:
    path: "{{ minio_binary_dir }}"
    state: directory
- name: Create minio log dir if necessary
  file:
    path: "{{ minio_log_dir }}"
    state: directory
    owner: "{{ minio_use_syslog|ternary('root', minio_user) }}"
    group: "{{ minio_user|ternary('root', minio_user) }}"
  when: minio_setup_logging
- name: Create and set permissions on minio data directories
  file:
    path: "{{ item[1] }}"
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_user }}"
  with_subelements:
    - "{{ minio_instances }}"
    - "volumes"
- name: Create and set permissions on minio config directories
  file:
    path: "/home/{{ minio_user ~ '/.minio' ~ minio_name_separator ~ item.name }}"
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_user }}"
  with_items:
    - "{{ minio_instances }}"
...
