---
- name: Check for existing binary
  stat:
    path: "{{ minio_binary_dir }}/minio"
  register: minio_binary_stat_result
- name: Download minio server
  get_url:
    url: "{{ minio_download_url }}"
    dest: "{{ minio_download_dir }}"
    mode: 0755
  when: minio_always_update_binary or not minio_binary_stat_result.stat.exists
- name: Install minio binary
  copy:
    src: "{{ minio_download_dir }}/minio"
    dest: "{{ minio_binary_dir }}/minio"
    owner: "{{ minio_user }}"
    group: "{{ minio_user }}"
    mode: 0755
    remote_src: true
    force: true
  when: minio_always_update_binary
  notify: restart_minio
...
