---
- name: Copy minio syslog config if necessary
  template:
    src: minio-syslog.conf.j2
    dest: "/etc/rsyslog.d/minio{{ minio_name_separator ~ item.name }}.conf"
    owner: root
    group: root
  with_items: "{{ minio_instances }}"
  when: minio_use_syslog
  notify: restart_rsyslog
...
